
FROM node:20.0.0


WORKDIR /usr/src/app


COPY package*.json ./


RUN npm install

RUN npm install @mui/material @emotion/react @emotion/styled

COPY . .

RUN npm run build


EXPOSE 3000


CMD ["npm", "run", "dev"]